# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-08 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Divisions',
            fields=[
                ('divid', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, choices=[('art', 'art'), ('History', 'History'), ('avi', 'Aviation'), ('Bio', 'Biological'), ('Mari', 'Maritime'), ('sci', 'science')], max_length=20, null=True)),
                ('floorno', models.IntegerField(blank=True, null=True)),
                ('hallno', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('eid', models.IntegerField(primary_key=True, serialize=False)),
                ('etype', models.CharField(blank=True, max_length=20, null=True)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('itemid', models.IntegerField(primary_key=True, serialize=False)),
                ('date_acq', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('divid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Divisions')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('sname', models.CharField(blank=True, max_length=30, null=True)),
                ('job', models.CharField(blank=True, max_length=20, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('divid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Divisions')),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Exhibition')),
            ],
        ),
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('visitdate', models.DateField(blank=True, null=True)),
                ('adult_ticket', models.IntegerField(blank=True, null=True)),
                ('child_ticket', models.IntegerField(blank=True, null=True)),
                ('tran_no', models.AutoField(primary_key=True, serialize=False)),
                ('cost', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
            ],
        ),
    ]
