# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-21 05:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisions',
            name='divid',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='divisions',
            name='floorno',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='divisions',
            name='hallno',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='eid',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='etype',
            field=models.CharField(blank=True, choices=[('art', 'art'), ('History', 'History'), ('avi', 'Aviation'), ('Bio', 'Biological'), ('Mari', 'Maritime'), ('sci', 'science')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='divid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Divisions'),
        ),
        migrations.AlterField(
            model_name='items',
            name='itemid',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='staff',
            name='divid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Divisions'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='eid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Exhibition'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='sid',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='adult_ticket',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='child_ticket',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
