# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-23 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180521_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
